{% set name = "fqtools" %}
{% set version = "2.3" %}
{% set md5 = "1cd84d52bb42ec5401f462aab7b0d2f9" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 1

source:
  url: https://github.com/alastair-droop/{{ name }}/archive/refs/tags/v2.3.tar.gz
  md5: {{ md5 }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib
    - htslib
  run:
    - zlib
    - htslib

test:
  commands:
    - fqtools -h

about:
  home: https://github.com/alastair-droop/fqtools
  license: GPLv3
  summary: 'An efficient FASTQ manipulation suite.'
